#!/usr/bin/env python3

import click
import stitch


@click.command()
@click.argument('source_dir', type=click.Path(exists=True, file_okay=False))
@click.option(
    '--output', '-o', default='stitched_image.jpg', show_default=True,
    help='The file name of the output image.'
)
@click.option(
    '--verbose', '-v', is_flag=True,
    help='Print detailed log messages.'
)
def main(source_dir, output, verbose):
    if verbose:
        print('Input parameters\n----------------'
              f'\nsource directory: {source_dir}'
              f'\noutput file: {output}'
              )


if __name__ == "__main__":
    main()
